services:

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/api/:/src/api/
    command: fastapi run src/api/app.py

  # webapp:
  #   build:
  #     context: ./ui/
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - ./ui/:/app/
  #   working_dir: /app
  #   entrypoint: ["streamlit", "run", "main.py"]
  #   depends_on:
  #     - 'api'
  #     - 'storage'
  #   profiles:
  #     - ''
  #     - webapp
  #     - fullstack
