services:

  api:
    build: .
    ports:
      - "8000:200"
    volumes:
      - ./src/api/:/app/src/api/
    command: fastapi run src/api/app.py

  ui:
    build: .
    expose:
      - 8501
    volumes:
      - ./src/ui/:/app/src/ui/
    command: streamlit run src/ui/app.py --server.runOnSave True
    depends_on:
      - api

  nginx:
    build: ./nginx
    ports:
      - 2:2
    depends_on:
      - api
      - ui
