services:

  api:
    build: .
    expose:
      - 200
    volumes:
      - ./src/api/:/app/src/api/
    command: fastapi run src/api/app.py --host 0.0.0.0 --port 200
    networks:
      - web

  prodtrack:
    build: .
    expose:
      - 8501
    volumes:
      - ./src/ui/:/app/src/ui/
    command: streamlit run src/ui/app.py
    depends_on:
      - api
    networks:
      - web

  nginx:
    build: ./nginx
    depends_on:
      - api
      - prodtrack
    expose:
      - 80
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOST=prodtrack.charlieavery.site
      - LETSENCRYPT_HOST=prodtrack.charlieavery.site
    networks:
      - web

networks:
  web:
    external: true
