services:

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/api/:/app/src/api/
    command: fastapi run src/api/app.py

  ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./src/ui/:/app/src/ui/
    command: streamlit run src/ui/app.py --server.runOnSave True
    depends_on:
      - api
